spring:
    application:
        name: mediamaestro
    datasource:
        url: jdbc:postgresql://localhost:5432/mediamaestro
        username: yourUsername
        password: yourPassword
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
