name: Java Maven Build & Publish Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: cd backend && mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Run Maven to verify and build any additional artifacts
      - run: cd backend && mvn --batch-mode --update-snapshots verify

      # Create staging directory and copy the JAR file to it
      - run: mkdir backend/staging && cp backend/target/*.jar backend/staging

      # Upload the artifact
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: backend/staging
